#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

# Determine the directory this script resides in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

pushd $SCRIPT_DIR >> /dev/null

    export macos_vm_vars_file="$SCRIPT_DIR/macos-virtualbox.conf"

    /usr/local/bin/bash ./macos-virtualbox/macos-guest-virtualbox.sh

popd >> /dev/null

