language: cpp
os: osx

addons:
  homebrew:
    update: true
    packages:
      - freetype
      - gettext
      - irrlicht
      - libogg
      - libvorbis
      - luajit

install:
  - git remote add upstream https://github.com/padresmurfa/minetest -t master -f
  - git checkout upstream/master
  - git clone --depth=1 https://github.com/padresmurfa/minetest_game games/minetest_game

script:
  - cmake
    -DVERSION_EXTRA=dev-$(sw_vers -productVersion)
    -DCMAKE_BUILD_TYPE=Release -DENABLE_FREETYPE=1 -DENABLE_LEVELDB=0 -DENABLE_GETTEXT=1
    -DENABLE_REDIS=0 -DBUILD_SERVER=0 -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext
    -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib"
  - make package

before_deploy:
  - git remote set-url origin https://${GITHUB_OAUTH_TOKEN}@github.com/padresmurfa/minetest
  - git remote set-branches --add origin master
  - git fetch origin
  - git push origin upstream/master:master
  - export TRAVIS_TAG=$(date +'%Y-%m-%d')

deploy:
  provider: releases
  name: ${TRAVIS_TAG}
  token: ${GITHUB_OAUTH_TOKEN}
  skip_cleanup: true
  file_glob: true
  file: "*.zip"
  overwrite: true
  target_commitish: master
  on:
    branch: builds-osx
