#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

VOLUME=$1

# if the docker volume exists, a string will be returned, otherwise empty will be returned
docker volume ls --quiet --filter "name=$VOLUME"
