#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

# Determine the directory this script resides in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SOURCE_DIR="$SCRIPT_DIR/../../../source"

USERANDHOST=$("$SCRIPT_DIR/info/build_machine/username_and_hostname")

############################################################################################
# SYNC FILES TO BUILD
############################################################################################

function list_uninteresting_files() {
    local DIR=$1
    pushd "$DIR" >> /dev/null
    git clean -dXn \
      | sed "s/Would remove //g" \
      | while read line; do \
        echo "$DIR/$line"; \
      done
    popd >> /dev/null
}

RSYNC_EXCLUDE=$(mktemp)

list_uninteresting_files "$SOURCE_DIR/games/minetest_game" >> "$RSYNC_EXCLUDE"
list_uninteresting_files "$SOURCE_DIR/minetest" >> "$RSYNC_EXCLUDE"

echo "Synchronizing files from '$SOURCE_DIR/' to '$HOME/minetest/'"
time rsync --verbose --archive --safe-links --executability --acls --whole-file \
      --ignore-times --exclude-from="$RSYNC_EXCLUDE" \
      --human-readable \
      "$SOURCE_DIR/" "$USERANDHOST:$HOME/minetest/"
echo ""
echo "Done"

rm "$RSYNC_EXCLUDE"

