#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

USER=$(whoami)

docker build \
  --build-arg USERNAME=$USER \
  --build-arg UID=$UID \
  --tag minetest-development-with-osx-and-docker-image \
  --file ./Dockerfile \
  .
