#!/bin/bash

# determine the absolute directory name of source
pushd ../source 2>&1 >> /dev/null
SOURCE_DIRECTORY=$(pwd)
popd 2>&1 >> /dev/null

user=$(whoami)

# run our docker container
# ... detached from this shell
# ... removing it automatically when it is stopped
# ... using a fixed name, minetest, for the running container
# ... mounting the relevant git-repositories into the container
# ... and selecting our docker image, which is named padresmurfa/minetest-development-with-osx-and-docker-image
docker run \
  --detach --tty \
  --rm \
  --name minetest \
  --volume $SOURCE_DIRECTORY/minetest:/home/$user/build/minetest \
  --volume $SOURCE_DIRECTORY/games:/home/$user/build/games \
  padresmurfa/minetest-development-with-osx-and-docker-image
