#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

# Determine the directory this script resides in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

IS_RUNNING=$("$SCRIPT_DIR/info/is_docker_container_running")
if [[ -n $IS_RUNNING ]]; then
  >&2 echo "The 'minetest' container was already running"
  exit 1
else
  # determine the absolute directory name of source
  pushd ../../../source >> /dev/null
  SOURCE_DIRECTORY=$(pwd)
  popd >> /dev/null
  if [[ ! -d $SOURCE_DIRECTORY ]]; then
    >&2 echo "Could not find directory '$SOURCE_DIRECTORY'"
    exit 1
  fi

  # determine the user's username
  USERNAME=$(whoami)

  EXPOSE_MINETEST_SERVER_ON_PORT=11001

  # run our docker container
  # ... detached from this shell
  # ... removing it automatically when it is stopped
  # ... using a fixed name, minetest, for the running container
  # ... granting read-only access to the shared_with_container folder
  # ... exposing the minetest server on port 11001
  # ... and selecting our docker image, which is named minetest-development-with-osx-and-docker-image
  docker run \
    --detach --tty \
    --rm \
    --name "minetest" \
    --publish 127.0.0.1:11001:11001/tcp \
    --publish 127.0.0.1:11001:11001/udp \
    --mount "type=bind,source=$SOURCE_DIRECTORY,destination=/home/$USERNAME/.shared_from_host,readonly" \
    --mount "type=volume,source=minetest-source,destination=/home/$USERNAME/source" \
    --mount "type=volume,source=minetest-servers,destination=/home/$USERNAME/servers" \
    minetest-development-with-osx-and-docker-image

  CONTAINER_ID=$("$SCRIPT_DIR/info/get_docker_container_id")
  CONTAINER_IPADDRESS=$("$SCRIPT_DIR/info/get_docker_container_ipaddress")
  echo "Started 'minetest' as a docker container with ID $CONTAINER_ID and IP address $CONTAINER_IPADDRESS"
  echo "... bind-mounted $SOURCE_DIRECTORY into the container as /home/$USERNAME/.shared_from_host"
  echo "... mounted the docker volume 'minetest' into the container as /home/$USERNAME/source"
fi
