#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail

VOLUME=$1

# Determine the directory this script resides in
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

EXISTS=$("$SCRIPT_DIR/info/does_docker_volume_exist" "$VOLUME")
if [[ -n $EXISTS ]]; then
  >&2 echo "The '$VOLUME' volume already exists"
  exit 1
else
  CREATED=$(docker volume create $VOLUME)
  echo "Created docker volume '$CREATED'"
fi
