#!/bin/bash

# see e.g. https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425 for details
set -e
set -u
set -o pipefail


############################################################################################
# BUILD Terasology
############################################################################################

pushd "$HOME/shared_with_host/source/minetest" >> /dev/null

cmake . \
    -DCMAKE_BUILD_TYPE=Release -DENABLE_FREETYPE=TRUE -DENABLE_LEVELDB=TRUE -DENABLE_GETTEXT=TRUE \
    -DENABLE_REDIS=FALSE -DBUILD_CLIENT=TRUE -DBUILD_SERVER=FALSE -DCUSTOM_GETTEXT_PATH=/usr/local/opt/gettext \
    -DCMAKE_EXE_LINKER_FLAGS="-L/usr/local/lib"

NUMBER_OF_PROCESSORS=$(nproc)
make -j"$NUMBER_OF_PROCESSORS"

popd >> /dev/null
